# Generated by Django 5.1.11 on 2026-06-25 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Charger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("charger_name", models.CharField(max_length=100)),
                (
                    "charger_type",
                    models.CharField(
                        choices=[("AC", "AC"), ("DC", "DC")], max_length=50
                    ),
                ),
                ("power_output", models.IntegerField(help_text="kW")),
                ("price_per_kwh", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("busy", "Busy"),
                            ("offline", "Offline"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chargers",
                        to="stations.chargingstation",
                    ),
                ),
            ],
        ),
    ]
