# Generated by Django 5.1.11 on 2026-07-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='mfa_secret',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
