# Generated by Django 6.0.5 on 2026-05-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_owner_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_owner_approved',
            field=models.BooleanField(default=False),
        ),
    ]
