# Generated by Django 6.0.5 on 2026-05-25 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_owner_approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_owner_verified',
        ),
    ]
