# Generated by Django 5.1.11 on 2026-06-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chargers", "0001_initial"),
        ("slots", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="is_booked",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="slot",
            index=models.Index(
                fields=["charger", "is_booked"], name="slots_slot_charger_183243_idx"
            ),
        ),
    ]
