# Generated by Django 5.1.11 on 2026-06-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargingstation",
            name="city",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="chargingstation",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
    ]
